export const products = [
  {
    title: "Magnetite",
    category: 8,
    price: 89.0,
    img: "./src/assets/img/1.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorare",
    category: 2,
    price: 66.0,
    img: "./src/assets/img/2.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: 8,
    price: 50.0,
    img: "./src/assets/img/3.jpg",
    band: "Nirvana",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: 1,
    price: 22.0,
    img: "./src/assets/img/4.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
  {
    title: "Thriller",
    category: 1,
    price: 30.0,
    img: "./src/assets/img/5.jpg",
    band: "Michael Jackson",
    year: 1982,
    id: 4,
  },
  {
    title: "Back in Black",
    category: 8,
    price: 45.0,
    img: "./src/assets/img/6.jpg",
    band: "AC/DC",
    year: 1980,
    id: 5,
  },
  {
    title: "The Eminem Show",
    category: 7,
    price: 25.0,
    img: "./src/assets/img/7.jpg",
    band: "Eminem",
    year: 2002,
    id: 6,
  },
  {
    title: "Legend",
    category: 9,
    price: 35.0,
    img: "./src/assets/img/8.jpg",
    band: "Bob Marley",
    year: 1984,
    id: 7,
  },
  {
    title: "Unplugged",
    category: 8,
    price: 28.0,
    img: "./src/assets/img/9.jpg",
    band: "Eric Clapton",
    year: 1992,
    id: 8,
  },
  {
    title: "The Dark Side of the Moon",
    category: 8,
    price: 40.0,
    img: "./src/assets/img/10.jpg",
    band: "Pink Floyd",
    year: 1973,
    id: 9,
  },
  {
    title: "Bad",
    category: 1,
    price: 32.0,
    img: "./src/assets/img/11.jpg",
    band: "Michael Jackson",
    year: 1987,
    id: 10,
  },
  {
    title: "Nevermind",
    category: 8,
    price: 33.0,
    img: "./src/assets/img/12.jpg",
    band: "Nirvana",
    year: 1991,
    id: 11,
  },
  {
    title: "Jota Quest Acústico",
    category: 2,
    price: 20.0,
    img: "./src/assets/img/13.jpg",
    band: "Jota Quest",
    year: 2003,
    id: 12,
  },
  {
    title: "Gratitude",
    category: 7,
    price: 27.0,
    img: "./src/assets/img/14.jpg",
    band: "Earth, Wind & Fire",
    year: 1975,
    id: 13,
  },
  {
    title: "Abbey Road",
    category: 8,
    price: 38.0,
    img: "./src/assets/img/15.jpg",
    band: "The Beatles",
    year: 1969,
    id: 14,
  },
  {
    title: "Back to Black",
    category: 2,
    price: 24.0,
    img: "./src/assets/img/16.jpg",
    band: "Amy Winehouse",
    year: 2006,
    id: 15,
  },
  {
    title: "Rage Against the Machine",
    category: 8,
    price: 31.0,
    img: "./src/assets/img/17.jpg",
    band: "Rage Against the Machine",
    year: 1992,
    id: 16,
  },
  {
    title: "Ao Vivo",
    category: 5,
    price: 29.0,
    img: "./src/assets/img/18.jpg",
    band: "Luiz Gonzaga",
    year: 1984,
    id: 17,
  },
  {
    title: "The Marshall Mathers LP",
    category: 7,
    price: 26.0,
    img: "./src/assets/img/19.jpg",
    band: "Eminem",
    year: 2000,
    id: 18,
  },
  {
    title: "Darkness on the Edge of Town",
    category: 8,
    price: 42.0,
    img: "./src/assets/img/20.jpg",
    band: "Bruce Springsteen",
    year: 1978,
    id: 19,
  },
];


export const categories = [
  "Todos",
  "Pop",
  "MPB",
  "Forró",
  "Samba",
  "Baião",
  "Rap",
  "Hip-Hop",
  "Rock",
  "Reggae",
  "Country",
  "Gospel",
];
